apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: log-platform
resources:
  - https://raw.githubusercontent.com/Altinity/clickhouse-operator/master/deploy/operator/clickhouse-operator-install-bundle.yaml
