apiVersion: v1
kind: Namespace
metadata:
  name: log-platform
  labels:
    app.kubernetes.io/name: log-platform
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: log-platform
