apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: log-platform
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: log-platform
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - 'alertmanager.log-platform.svc:9093'
    scrape_configs:
      - job_name: 'vector'
        static_configs:
          - targets: ['vector.log-platform.svc:9598']
      - job_name: 'kafka'
        static_configs:
          - targets: ['log-kafka-kafka-bootstrap.log-platform.svc:9404']
      - job_name: 'clickhouse'
        static_configs:
          - targets: ['chi-log-clickhouse-logs-0-0.log-platform.svc:9363']
      - job_name: 'minio'
        metrics_path: /minio/v2/metrics/cluster
        static_configs:
          - targets: ['minio.log-platform.svc:9000']
      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana.log-platform.svc:3000']
      - job_name: 'query-api'
        static_configs:
          - targets: ['query-api.log-platform.svc:8080']
